# Production overrides for Hook0
api:
  replicaCount: 2
  env:
    CORS_ALLOWED_ORIGINS: 'https://hook0.fimento.io'
    APP_URL: 'https://hook0.fimento.io'
  ingress:
    hosts:
      - host: api.hook0.fimento.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: api-hook0-fimento-io-tls
        hosts:
          - api.hook0.fimento.io

frontend:
  replicaCount: 2
  env:
    API_ENDPOINT: 'https://api.hook0.fimento.io/api/v1'
  ingress:
    hosts:
      - host: hook0.fimento.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: hook0-fimento-io-tls
        hosts:
          - hook0.fimento.io

outputWorker:
  replicaCount: 2
