# Staging overrides for Hook0
api:
  env:
    CORS_ALLOWED_ORIGINS: 'https://hook0.staging.fimento.io'
    APP_URL: 'https://hook0.staging.fimento.io'
  ingress:
    hosts:
      - host: api.hook0.staging.fimento.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: api-hook0-staging-fimento-io-tls
        hosts:
          - api.hook0.staging.fimento.io

frontend:
  env:
    API_ENDPOINT: 'https://api.hook0.staging.fimento.io/api/v1'
  ingress:
    hosts:
      - host: hook0.staging.fimento.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: hook0-staging-fimento-io-tls
        hosts:
          - hook0.staging.fimento.io
