# Production overrides for Hook0

api:
  replicaCount: 2
  env:
    CORS_ALLOWED_ORIGINS: 'https://hook0.fimento.io'
    APP_URL: 'https://hook0.fimento.io'
    DISABLE_TARGET_IP_CHECK: 'false'
  ingress:
    className: 'kong-external'
    hosts:
      - host: hook0-api.fimento.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: hook0-api-fimento-io-tls
        hosts:
          - hook0-api.fimento.io

frontend:
  enabled: true
  env:
    API_ENDPOINT: 'https://hook0-api.fimento.io/api/v1'

outputWorker:
  replicaCount: 2
