{{- if and .Values.frontend.enabled .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hook0.fullname" . }}-frontend
  labels:
    {{- include "hook0.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    {{- range .Values.frontend.ingress.hosts }}
    external-dns.alpha.kubernetes.io/hostname: {{ .host }}
    {{- break }}
    {{- end }}
    konghq.com/protocols: "https"
    konghq.com/https-redirect-status-code: "301"
    {{- with .Values.frontend.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.frontend.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.frontend.ingress.tls }}
  tls:
    {{- range .Values.frontend.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.frontend.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "hook0.fullname" $ }}-frontend
                port:
                  number: 80
          {{- end }}
    {{- end }}
{{- end }}
